-- Create two trainer records
INSERT INTO CANTRAINDB.TRAINER(TRAINER_ID, USER_ID, TRAINER_WEBSITE_URL, TRAINER_YOUTIBE_URL, TRAINER_INSTAGRAM_URL)
VALUES (10, 1, 'https://vanderbilt.edu', 'https://www.youtube.com', null);

INSERT INTO CANTRAINDB.TRAINER(TRAINER_ID, USER_ID, TRAINER_WEBSITE_URL, TRAINER_YOUTIBE_URL, TRAINER_INSTAGRAM_URL)
VALUES (10, 1, null, null, 'https://www.instagram.com/vanderbiltu/');
