-- Create 4 client records
INSERT INTO CANTRAINDB.CLIENT (CLIENT_ID, USER_ID)
VALUES (20, 3);

INSERT INTO CANTRAINDB.CLIENT (CLIENT_ID, USER_ID)
VALUES (21, 4);

INSERT INTO CANTRAINDB.CLIENT (CLIENT_ID, USER_ID)
VALUES (22, 5);

INSERT INTO CANTRAINDB.CLIENT (CLIENT_ID, USER_ID)
VALUES (23, 6);
