-- Create a trainer plan record for each trainer
INSERT INTO CANTRAINDB.TRAINER_PLAN (TRAINER_PLAN_ID, TRAINER_ID, PAYMENT_PLAN_ID, DATE_STARTED, BILLED_PRICE, TRAINER_PLAN_ACTIVE)
VALUES (100, 10, 1, NOW(), 0, True);

-- Create a trainer plan record for each trainer
INSERT INTO CANTRAINDB.TRAINER_PLAN (TRAINER_PLAN_ID, TRAINER_ID, PAYMENT_PLAN_ID, DATE_STARTED, BILLED_PRICE, TRAINER_PLAN_ACTIVE)
VALUES (200, 20, 1, NOW(), 0, True);
