-- Create Client Trainer records for the 4 clients
INSERT INTO CANTRAINDB.CLIENT_TRAINER (CLIENT_ID, TRAINER_ID)
VALUES (20, 10);

INSERT INTO CANTRAINDB.CLIENT_TRAINER (CLIENT_ID, TRAINER_ID)
VALUES (20, 20);

INSERT INTO CANTRAINDB.CLIENT_TRAINER (CLIENT_ID, TRAINER_ID)
VALUES (21, 10);

INSERT INTO CANTRAINDB.CLIENT_TRAINER (CLIENT_ID, TRAINER_ID)
VALUES (22, 20);

INSERT INTO CANTRAINDB.CLIENT_TRAINER (CLIENT_ID, TRAINER_ID)
VALUES (23, 20);