-- Create exercise records -- Trainer 1
-- Push A
INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(1, 10, 'Bench Press', 'Barbell bench press', 'https://www.youtube.com/watch?v=HnQGKxU3eds', True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(2, 10, 'Behind the Head Shoudler Press', 'Ideally performed on a smith machine. Do not bring down under your ears behind your head', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(3, 10, 'Triceps Dips', 'Start with body weight. Can add weight as you progress', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(4, 10, 'Cable Crossover', 'Can be performed with the cables high or low', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(5, 10, 'Overhead Triceps Pull', 'Pull straight above head ', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(6, 10, 'Seated Lat Raise', 'Slow and controlled', null, True);

-- Pull A

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(7, 10, 'Deadlift', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(8, 10, 'Chin ups', 'Forearms facing you.', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(9, 10, 'Chest Supported Rows', null, null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(10, 10, 'Dumbbell Shoulder Shrug', 'Hold two dumbells on front edges of hips', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(11, 10, 'Barbell Biceps Curl', 'Standing using EZ bar', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(12, 10, 'Standing Cable Reverse Fly', null, null, True);

-- Legs A

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(13, 10, 'Back Squat', 'Focus on keeping a straight barpath', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(14, 10, 'Good Mornings', 'Hinge at the hips, keep legs straight', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(15, 10, 'Leg Press', 'Do not let your knees wobble. Keep knees in line with legs', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(16, 10, 'Reverse Hyperextension', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(17, 10, 'Seated Leg Curl', 'Seated leg curl machine', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(18, 10, 'Calf Raise', 'Use the leg press machine', null, False);

-- Push B

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(19, 10, 'Standing Overhead Press', 'Down to your chin. Do not lockout', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(20, 10, 'Incline Bench Press', 'Barbell or Dumbbell. Can vary.', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(21, 10, 'Close Grip Bench Press', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(22, 10, 'Cable Machine Fly', null, null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(23, 10, 'Triceps Cable Pulldown', 'Preferably a V bar', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(24, 10, 'Single Arm Row', 'Standing next to the cable machine. Perform the reps for each arm one at a time.', null, True);


-- Pull B

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(25, 10, 'Wide Grip Dead Lift', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(26, 10, 'Standing Barbell Row', 'Bent over.', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(27, 10, 'Pull ups', 'Forearms facing away from you', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(28, 10, 'Single Arm Dumbell Rows', 'Perform the reps for one arm at a time. Support yourself on another dumbell on the rack. Put the leg on the same side as the arm you are lifting with back', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(29, 10, 'Seated Biceps Curl', 'Low weight, full range of motion', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(30, 10, 'Reverse Deltoid Fly', 'On the fly machine', null, True);

-- Legs B

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(31, 10, 'Front Squat', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(32, 10, 'Romanian Deadlift (RDL)', 'Hinge from hips. Keep legs straight. Go down until you feel it in your hamstrings', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(33, 10, 'Hip Thrust', 'On the Smith Machine. Superset with goblet squat', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(34, 10, 'Goblet Squat', 'Superset with hip thrust', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(35, 10, 'Leg Extension Machine', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(36, 10, 'Hanging Leg Raises', 'Alternate between legs out and legs tucked in', null, False);
