-- Create exercise records -- Trainer 1
INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(1, 10, 'Bench Press', 'Barbell bench press', 'https://www.youtube.com/watch?v=HnQGKxU3eds', True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(2, 10, 'Behind the Head Shoudler Press', 'Ideally performed on a smith machine. Do not bring down under your ears behind your head', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(3, 10, 'Triceps Dips', 'Start with body weight. Can add weight as you progress', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(4, 10, 'Deadlift', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(5, 10, 'Chin ups', 'Forearms facing you.', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(6, 10, 'Dumbbell Shoulder Shrug', null, null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(7, 10, 'Back Squat', 'Focus on keeping a straight barpath', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(8, 10, 'Good Mornings', 'Hinge at the hips, keep legs straight', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(9, 10, 'Leg Press', 'Do not let your knees wobble. Keep knees in line with legs', null, False);

-- Trainer 2

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(10, 20, 'Standing Overhead Press', 'Down to your chin. Do not lockout', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(11, 20, 'Incline Bench Press', 'Barbell or Dumbbell. Can vary.', null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(12, 20, 'Close Grip Bench Press', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(13, 20, 'Wide Grip Dead Lift', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(14, 20, 'Standing Barbell Row', 'Bent over.', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(15, 20, 'Pull ups', 'Forearms facing away from you', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(16, 20, 'Front Squat', null, null, False);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(17, 20, 'Romanian Deadlift (RDL)', 'Hinge from hips. Keep legs straight. Go down until you feel it in your hamstrings', null, True);

INSERT INTO CANTRAINDB.EXERCISE (EXERCISE_ID, TRAINER_ID, EXERCISE_NAME, EXERCISE_INSTRUCTIONS, EXERCISE_VIDEO_LINK, PUBLIC_EXERCISE)
VALUES(18, 20, 'Hip Thrust', 'On the Smith Machine', null, False);
