-- Create 3 Workout Records for trainer ID 10
INSERT INTO CANTRAINDB.WORKOUT (WORKOUT_ID, TRAINER_ID, WORKOUT_NAME, WORKOUT_DESCRIPTION)
VALUES (50, 10, 'Push A', 'Pushing exercises focused around bench press.');

INSERT INTO CANTRAINDB.WORKOUT (WORKOUT_ID, TRAINER_ID, WORKOUT_NAME, WORKOUT_DESCRIPTION)
VALUES (55, 10, 'Pull A', 'Pulling exercises focused around deadlift.');

INSERT INTO CANTRAINDB.WORKOUT (WORKOUT_ID, TRAINER_ID, WORKOUT_NAME, WORKOUT_DESCRIPTION)
VALUES (60, 10, 'Legs A', 'Leg day focused around squats.');

-- Create 3 Workout Records
INSERT INTO CANTRAINDB.WORKOUT (WORKOUT_ID, TRAINER_ID, WORKOUT_NAME, WORKOUT_DESCRIPTION)
VALUES (65, 20, 'Push B', null);

INSERT INTO CANTRAINDB.WORKOUT (WORKOUT_ID, TRAINER_ID, WORKOUT_NAME, WORKOUT_DESCRIPTION)
VALUES (70, 20, 'Pull B', 'Lots of rows');

INSERT INTO CANTRAINDB.WORKOUT (WORKOUT_ID, TRAINER_ID, WORKOUT_NAME, WORKOUT_DESCRIPTION)
VALUES (75, 20, 'Legs B', 'Leg day focused around front squats');
