-- Create a regiment for Trainer Id 10 to assign
INSERT INTO CANTRAINDB.REGIMENT (REGIMENT_ID, TRAINER_ID, REGIMENT_NAME, REGIMENT_CYCLE_LENGTH)
VALUES (200, 10, 'Push/Pull 1', 12);

-- Create a regiment for Trainer Id 20 to assign
INSERT INTO CANTRAINDB.REGIMENT (REGIMENT_ID, TRAINER_ID, REGIMENT_NAME, REGIMENT_CYCLE_LENGTH)
VALUES (225, 20, 'Push/Pull 2', 15);
