-- Assign exercies to workouts
-- Assigning exercises to Push A (Id 50) workout which will belong to Trainer Id 10 for Trainer User jane.trainer@gmail.com
INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (1, 50, 1, 1, 5, 3, null, null, 'Five sets of 3 reps at heavy, challenging weight. Make sure to thoroughly warm up. After the 5 sets. Drop weight 20% and do as many quality reps as possible.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (2, 50, 2, 2, 3, 8, null, null, 'Three sets to get 25 total reps.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (3, 50, 3, 3, 3, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (4, 50, 4, 4, 19, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (5, 50, 5, 5, 20, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (6, 50, 6, 6, 21, 5, 10, null, null, null);

-- Assigning exercises to Pull A (Id 55) workout which will also belong to Trainer Id 10

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (7, 55, , 1);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (8, 55, );

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

-- Assigning Exercises to Legs A

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();
