-- Assign exercies to workouts
INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSINGED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES ();
