-- Assign exercies to workouts
-- Assigning exercises to Push A (Id 50) workout which will belong to Trainer Id 10 for Trainer User jane.trainer@gmail.com
INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (1, 50, 1, 1, 5, 3, null, null, 'Five sets of 3 reps at heavy, challenging weight. Make sure to thoroughly warm up. After the 5 sets. Drop weight 20% and do as many quality reps as possible.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (2, 50, 2, 2, 3, 8, null, null, 'Three sets to get 25 total reps.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (3, 50, 3, 3, 3, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (4, 50, 4, 4, 19, 5, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (5, 50, 5, 5, 20, 5, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (6, 50, 6, 6, 21, 5, null, null, null);

-- Assigning exercises to Pull A (Id 55) workout which will also belong to Trainer Id 10

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (7, 55, 7, 1, 5, 3, null, null, 'Five sets of 3 reps at heavy, challenging weight. Then 6th set of as many quality reps as possible at 80% weight. Aim for 8 - 15.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (8, 55, 8, 2, 3, 8, null, null, 'Three sets to get 25 total reps.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (9, 55, 9, 3, 3, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (10, 55, 10, 4, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (11, 55, 11, 5, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (12, 55, 12, 6, 5, 10, null, null, null);

-- Assigning Exercises to Legs A

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (13, 60, 13, 1, 5, 3, null, null, 'Five sets of 3 reps at heavy, challenging weight. Then 6th set of as many quality reps as possible at 80% weight. Aim for 8 - 15.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (14, 60, 14, 2, 3, 8, null, null, 'Three sets to get total of 25 reps.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (15, 60, 15, 3, 3, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (16, 60, 16, 4, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (17, 60, 17, 5, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (18, 60, 18, 6, 5, 10, null, null, null);

-- Assigning Exercises to Push B
INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (19, 65, 19, 1, 5, 3, null, null, 'Five sets of 3 reps at heavy, challenging weight. Then 6th set of as many quality reps as possible at 80% weight. Aim for 8 - 15.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (20, 65, 20, 2, 3, 8, null, null, 'Three sets to get total of 25 reps.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (21, 65, 21, 3, 3, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (22, 65, 22, 4, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (23, 65, 23, 5, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (24, 65, 24, 6, 5, 10, null, null, null);

-- Assigning Exercises To Pull B
INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (25, 70, 25, 1, 5, 3, null, null, 'Five sets of 3 reps at heavy, challenging weight. Then 6th set of as many quality reps as possible at 80% weight. Aim for 8 - 15.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (26, 70, 26, 2, 3, 8, null, null, 'Three sets for a total of 25 reps.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (27, 70, 27, 3, 3, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (28, 70, 28, 4, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (29, 70, 29, 5, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (30, 70, 30, 6, 5, 10, null, null, null);

-- Assigning Exercises To Legs B 
INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (31, 75, 31, 1, 5, 3, null, null, 'Five sets of 3 reps at heavy, challenging weight. Then 6th set of as many quality reps as possible at 80% weight. Aim for 8 - 15.');

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (32, 75, 32, 2, 3, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (33, 75, 33, 3, 3, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (34, 75, 34, 4, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (35, 75, 35, 5, 5, 10, null, null, null);

INSERT INTO CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID, WORKOUT_ID, EXERCISE_ID, EXERCISE_ORDER, ASSIGNED_SETS, ASSIGNED_REPS, ASSIGNED_DURATION, ASSIGNED_DISTANCE, ASSIGNED_EXERCISE_NOTES)
VALUES (36, 75, 36, 6, 5, 10, null, null, null);