-- Build out Push Pull Legs 1 regiment (Id 200) for Trainer Id 10
INSERT INTO CANTRAINDB.ASSIGNED_WORKOUT (ASSIGNED_WORKOUT_ID, REGIMENT_ID, WORKOUT_ID, WORKOUT_ORDER, ASSIGNED_WORKOUT_NOTES)
VALUES (1, 200, 50, 1, 'Make sure to have a spotter for benching heavy.');

INSERT INTO CANTRAINDB.ASSIGNED_WORKOUT (ASSIGNED_WORKOUT_ID, REGIMENT_ID, WORKOUT_ID, WORKOUT_ORDER, ASSIGNED_WORKOUT_NOTES)
VALUES (1, 200, 55, 1, null);

INSERT INTO CANTRAINDB.ASSIGNED_WORKOUT (ASSIGNED_WORKOUT_ID, REGIMENT_ID, WORKOUT_ID, WORKOUT_ORDER, ASSIGNED_WORKOUT_NOTES)
VALUES (1, 200, 60, 1, null);

INSERT INTO CANTRAINDB.ASSIGNED_WORKOUT (ASSIGNED_WORKOUT_ID, REGIMENT_ID, WORKOUT_ID, WORKOUT_ORDER, ASSIGNED_WORKOUT_NOTES)
VALUES (1, 200, 65, 1, null);

INSERT INTO CANTRAINDB.ASSIGNED_WORKOUT (ASSIGNED_WORKOUT_ID, REGIMENT_ID, WORKOUT_ID, WORKOUT_ORDER, ASSIGNED_WORKOUT_NOTES)
VALUES (1, 200, 70, 1, null);

INSERT INTO CANTRAINDB.ASSIGNED_WORKOUT (ASSIGNED_WORKOUT_ID, REGIMENT_ID, WORKOUT_ID, WORKOUT_ORDER, ASSIGNED_WORKOUT_NOTES)
VALUES (1, 200, 75, 1, null);
