-- Build out Push Pull Legs 1 regiment (Id 200) for Trainer Id 10
INSERT INTO CANTRAINDB.ASSIGNED_WORKOUT (ASSIGNED_WORKOUT_ID, REGIMENT_ID, WORKOUT_ID, WORKOUT_ORDER, ASSIGNED_WORKOUT_NOTES)
VALUES (1, );
