
-- Assign the Push/Pull/Legs regiment (Id 200) to danmopsick@gmail.com (Client Id 21)
INSERT INTO CANTRAINDB.ASSIGNED_REGIMENT (ASSIGNED_REGIMENT_ID, REGIMENT_ID, CLIENT_ID, CURRENT_CYCLE, REGIMENT_ACTIVE, REGIMENT_ARCHIVE, REGIMENT_STATUS)
VALUES (1, 200, 21, 1, true, false, 0);
