// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBUpVWn9nRVJdFugf86UIqlIvAlAztKQCA',
    appId: '1:425822633989:web:7fa37338efe7def8e1dc6c',
    messagingSenderId: '425822633989',
    projectId: 'cantrain-3b05d',
    authDomain: 'cantrain-3b05d.firebaseapp.com',
    storageBucket: 'cantrain-3b05d.appspot.com',
    measurementId: 'G-MKCZMG177G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBZxzfxvLlIoEZxK-l2lQLe53VGuua1Yz4',
    appId: '1:425822633989:android:28dbbbe91e798684e1dc6c',
    messagingSenderId: '425822633989',
    projectId: 'cantrain-3b05d',
    storageBucket: 'cantrain-3b05d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvB5BXLDzWz9jX_ygnGmTODhZxMiwLpfQ',
    appId: '1:425822633989:ios:ef0064fbb24c4a5be1dc6c',
    messagingSenderId: '425822633989',
    projectId: 'cantrain-3b05d',
    storageBucket: 'cantrain-3b05d.appspot.com',
    iosClientId: '425822633989-nlphesp9qam6bom3i0hbql4hv29g9pvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.cantrain',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvB5BXLDzWz9jX_ygnGmTODhZxMiwLpfQ',
    appId: '1:425822633989:ios:ef0064fbb24c4a5be1dc6c',
    messagingSenderId: '425822633989',
    projectId: 'cantrain-3b05d',
    storageBucket: 'cantrain-3b05d.appspot.com',
    iosClientId: '425822633989-nlphesp9qam6bom3i0hbql4hv29g9pvp.apps.googleusercontent.com',
    iosBundleId: 'com.example.cantrain',
  );
}
