-- ---------------------------------------
-- -- DDL Statements for the USER Table
-- ---------------------------------------

CREATE TABLE CANTRAINDB.USER (
    USER_ID                     INT NOT NULL AUTO_INCREMENT,
    USER_SETTINGS_ID            INT NOT NULL,
    USER_ROLE_ID                INT NOT NULL,
    USER_EMAIL                  VARCHAR(128) NOT NULL,
    USER_FIRST_NAME             VARCHAR(128) NOT NULL,
    USER_LAST_NAME              VARCHAR(128) NOT NULL,
    USER_PREFERRED_NAME         VARCHAR(128),
    USER_ACTIVE                 BOOLEAN NOT NULL,
    UNITS_OF_MEASUREMENT_SWITCH BOOLEAN NOT NULL,
    PRIMARY KEY (USER_ID)
);

-- DDL Statements for indexes on USER Table
CREATE UNIQUE INDEX USER_UQ1 
ON CANTRAINDB.USER (USER_ID);

CREATE INDEX USER_IDX2
ON CANTRAINDB.USER (USER_SETTINGS_ID);

-- DDL Statement for Foreign Keys on USER Table
ALTER TABLE CANTRAINDB.USER
ADD FOREIGN KEY (USER_SETTINGS_ID) REFERENCES CANTRAINDB.USER_SETTINGS (USER_SETTINGS_ID);

ALTER TABLE CANTRAINDB.USER
ADD FOREIGN KEY (USER_ROLE_ID) REFERENCES CANTRAINDB.USER_ROLE (USER_ROLE_ID);
