------------------------------------------------
---- DDL Statements for the TRAINER_PLAN Table
------------------------------------------------

CREATE TABLE TRAINER_PLAN (
    TRAINER_PLAN_ID INT NOT NULL AUTO_INCREMENT,
    TRAINER_ID      INT NOT NULL,
    PLAN_ID         INT NOT NULL,
    DATE_STARTED    TIMESTAMP NOT NULL.
    BILLED_PRICE    DECIMAL(10, 2)
);

-- DDL Statements for indexes on TRAINER_PLAN Table
CREATE UNIQUE INDEX TRAINER_PLAN_UNQ1
ON TRAINER_PLAN ("TRAINER_PLAN_ID");

CREATE INDEX TRAINER_PLAN_IDX2
ON TRAINER_PLAN ("TRAINER_ID");

-- DDL Statement for Foreign Keys on TRAINER_PLAN Table
ALTER TABLE TRAINER_PLAN
ADD FOREIGN KEY ("TRAINER_ID") REFERENCES TRAINER("TRAINER_ID");
