---------------------------------------------------
---- DDL Statements for the WORKOUT Table
---------------------------------------------------

CREATE TABLE CANTRAINDB.WORKOUT (
    WORKOUT_ID          INT NOT NULL AUTO_INCREMENT,
    TRAINER_ID          INT NOT NULL,
    WORKOUT_NAME        VARCHAR(256) NOT NULL,
    WORKOUT_DESCRIPTION VARCHAR(4096),
    PRIMARY KEY (WORKOUT_ID)
);

-- DDL Statements for indexes on ASSIGNED_WORKOUT Table
CREATE UNIQUE INDEX WORKOUT_UNQ1
ON WORKOUT (WORKOUT_ID);

CREATE INDEX WORKOUT_IDX2
ON WORKOUT (TRAINER_ID);

-- DDL Statement for Foreign Keys on ASSIGNED_WORKOUT Table
ALTER TABLE WORKOUT
ADD FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER (TRAINER_ID);
