-- --------------------------------------------------
-- -- DDL Statements for the ASSIGNED_EXERCISE Table
-- --------------------------------------------------

CREATE TABLE CANTRAINDB.ASSIGNED_EXERCISE (
    ASSIGNED_EXERCISE_ID    INT NOT NULL AUTO_INCREMENT,
    WORKOUT_ID              INT NOT NULL,
    EXERCISE_ID             INT NOT NULL,
    EXERCISE_ORDER          TINYINT,
    ASSIGNED_SETS           TINYINT,
    ASSIGNED_REPS           TINYINT,
    ASSIGNED_DURATION       VARCHAR(128),
    ASSIGNED_DISTANCE       VARCHAR(128),
    ASSIGNED_EXERCISE_NOTES VARCHAR(4096),
    PRIMARY KEY (ASSIGNED_EXERCISE_ID)
);

-- DDL Statements for indexes on ASSIGNED_EXERCISE Table
CREATE UNIQUE INDEX ASSIGNED_EXERCISE_UNQ1
ON CANTRAINDB.ASSIGNED_EXERCISE (ASSIGNED_EXERCISE_ID);

CREATE INDEX ASSIGNED_EXERCISE_IDX2
ON CANTRAINDB.ASSIGNED_EXERCISE (WORKOUT_ID);

CREATE INDEX ASSIGNED_EXERCISE_IDX3
ON CANTRAINDB.ASSIGNED_EXERCISE (EXERCISE_ID);

-- DDL Statement for Foreign Keys on ASSIGNED_EXERCISE Table
ALTER TABLE CANTRAINDB.ASSIGNED_EXERCISE 
ADD FOREIGN KEY (WORKOUT_ID) REFERENCES CANTRAINDB.WORKOUT (WORKOUT_ID);

ALTER TABLE CANTRAINDB.ASSIGNED_EXERCISE
ADD FOREIGN KEY (EXERCISE_ID) REFERENCES CANTRAINDB.EXERCISE (EXERCISE_ID);
