----------------------------------------------------
---- DDL Statements for the ASSIGNED_EXERCISE Table
----------------------------------------------------

CREATE TABLE ASSIGNED_EXERCISE (
    ASSIGNED_EXERCISE_ID INT NOT NULL AUTO_INCREMENT,
    REGIMENT_ID         INT NOT NULL,
    WORKOUT_ID          INT NOT NULL,
    WORKOUT_ORDER       TINYINT
)
 
-- DDL Statements for indexes on ASSIGNED_EXERCISE Table
CREATE UNIQUE INDEX ASSIGNED_EXERCISE_UNQ1
ON ASSIGNED_EXERCISE ("ASSIGNED_EXERCISE_ID")

CREATE INDEX ASSIGNED_EXERCISE_IDX2
ON ASSIGNED_EXERCISE ("REGIMENT_ID");

CREATE INDEX ASSIGNED_EXERCISE_IDX3
ON ASSIGNED_EXERCISE ("WORKOUT_ID");

ALTER TABLE ASSIGNED_EXERCISE
ADD PRIMARY KEY(ASSIGNED_EXERCISE_ID);

-- DDL Statement for Foreign Keys on ASSIGNED_EXERCISE Table
ALTER TABLE ASSIGNED_EXERCISE
ADD FOREIGN KEY ("REGIMENT_ID") REFERENCES REGIMENT("REGIMENT_ID");

ALTER TABLE ASSIGNED_EXERCISE
ADD FOREIGN KEY ("WORKOUT_ID") REFERENCES WORKOUT("WORKOUT_ID");
