-- -------------------------------------------------
-- -- DDL Statements for the EXECUTED_WORKOUT Table
-- -------------------------------------------------

CREATE TABLE CANTRAINDB.EXECUTED_WORKOUT (
    EXECUTED_WORKOUT_ID INT NOT NULL AUTO_INCREMENT,
    ASSIGNED_WORKOUT_ID INT NOT NULL,
    WORKOUT_START_TIME  TIMESTAMP NOT NULL,
    WORKOUT_END_TIME    TIMESTAMP NOT NULL,
    WORKOUT_NOTES       VARCHAR(4096),
    PRIMARY KEY (EXECUTED_WORKOUT_ID)
);

-- DDL Statements for indexes on EXECUTED_WORKOUT Table
CREATE UNIQUE INDEX EXECUTED_WORKOUT_UNQ1
ON CANTRAINDB.EXECUTED_WORKOUT (EXECUTED_WORKOUT_ID);

CREATE INDEX EXECUTED_WORKOUT_IDX2
ON CANTRAINDB.EXECUTED_WORKOUT (ASSIGNED_WORKOUT_ID);

-- DDL Statement for Foreign Keys on EXECUTED_WORKOUT Table
ALTER TABLE CANTRAINDB.EXECUTED_WORKOUT
ADD FOREIGN KEY (ASSIGNED_WORKOUT_ID) REFERENCES CANTRAINDB.ASSIGNED_WORKOUT ASSIGNED_WORKOUT_ID);
