----------------------------------------------------
---- DDL Statements for the EXERCISE_SET Table
----------------------------------------------------

CREATE TABLE EXERCISE_SET (
    EXERCISE_SET_ID      INT NOT NULL AUTO_INCREMENT,
    EXECUTED_EXERCISE_ID INT NOT NULL,
    EXERCISE_WEIGHT      TINYINT,
    EXERCISE_REPS        TINYINT
);

-- DDL Statements for indexes on EXERCISE_SET
CREATE UNIQUE INDEX EXERCISE_SET_UNQ1
ON EXERCISE_SET ("EXERCISE_SET_ID");

CREATE INDEX EXERCISE_SET_IDX2
ON EXERCISE_SET ("EXECUTED_EXERCISE_ID");

-- DDL Statement for Foreign Keys on EXERCISE_SET
ALTER TABLE EXERCISE_SET
ADD FOREIGN KEY ("EXECUTED_EXERCISE_ID") REFERENCES EXECUTED_EXERCISE("EXECUTED_EXERCISE_ID");
