----------------------------------------------------
---- DDL Statements for the CLIENT_TRAINER Table
----------------------------------------------------

CREATE TABLE CANTRAINDB.CLIENT_TRAINER (
    CLIENT_ID INT NOT NULL,
    TRAINER_ID INT NOT NULL
)

-- DDL Statements for indexes on CLIENT_TRAINER Table
CREATE UNIQUE INDEX CLIENT_TRAINER_UNQ1
ON CLIENT_TRAINER (CLIENT_ID, TRAINER_ID);

-- DDL Statement for Foreign Keys on CLIENT_TRAINER Table
ALTER TABLE CLIENT_TRAINER
ADD FOREIGN KEY (CLIENT_ID) REFERENCES CLIENT (CLIENT_ID);

ALTER TABLE CLIENT_TRAINER
ADD FOREIGN KEY (TRAINER_ID) REFERENCES TRAINER (TRAINER_ID);
