----------------------------------------------------
---- DDL Statements for the ASSIGNED_EXERCISE Table
----------------------------------------------------

CREATE TABLE ASSIGNED_EXERCISE (
    ASSIGNED_EXERCISE_ID INT NOT NULL AUTO_INCREMENT,
    EXERCISE_ID          INT NOT NULL,
    ASSIGNED_WORKOUT_ID  INT NOT NULL,
    ASSIGNED_SETS        TINYINT,
    ASSIGNED_REPS        TINYINT,
    EXERCISE_NOTES       VARCHAR(2048)
);

-- DDL Statements for indexes on ASSIGNED_EXERCISE Table
CREATE UNIQUE INDEX ASSIGNED_EXERCISE_UNQ1
ON ASSIGNED_EXERCISE ("ASSIGNED_EXERCISE_ID");

CREATE INDEX ASSIGNED_EXERCISE_IDX2
ON ASSIGNED_EXERCISE ("EXERCISED_ID");

CREATE INDEX ASSIGNED_EXERCISE_IDX3
ON ASSIGNED_EXERCISE ("ASSIGNED_WORKOUT_ID");

-- DDL Statement for Foreign Keys on ASSIGNED_EXERCISE Table
ALTER TABLE ASSIGNED_EXERCISE
ADD FOREIGN KEY ("EXERCISE_ID") REFERENCES EXERCISE("EXERCISE_ID");

ALTER TABLE ASSIGNED_EXERCISE
ADD FOREIGN KEY ("WORKOUT_ID") REFERENCES ASSIGNED_WORKOUT("ASSIGNED_WORKOUT_ID");
